### ISSUE TITLE
GPU not used on commercial version

### ISSUE THREAD

**Issue by jfvizoso** [emgucv/emgutf#13]
I have purchased the commercial version, but my model is still using CPU, although my PC supports CUDA (I can use GPU with Tensoflow in python)

Is there anything I must do to enable GPU? 

How can I be sure the dlls I got are the GPU-enabled ones?

**Comment by emgucv** [comment]
Hi, 

We have created a tutorial page to run though a few checklist items:
http://www.emgu.com/wiki/index.php/Using_Emgu_TF_with_GPU_(Commercial_Release)

Please follow the steps and see if you can run Emgu TF with GPU. If you are still having issues, please send us the system information as listed on the above page and we can take a further look.

Thanks.
