### ISSUE TITLE
Looking for equivalent to cvFindExtrinsicCameraParams2

### ISSUE THREAD

**Issue by corcoranj0** [emgucv/emgutf#14]
I have some code that is working with the v2.1.0 version of the library and I need to upgrade to the current. However a lot of the methods I was previously using don't seem to exist anymore. 

How can I find the equivalent to these methods in order to formulate the same result? 

       `//Local Variable Declaration
        var worldPoints = CvInvoke.cvCreateMat(3, 4, DepthType.Cv64F);
        var imagePoints = CvInvoke.cvCreateMat(2, 4, DepthType.Cv64F);
        var translation = CvInvoke.cvCreateMat(3, 1, DepthType.Cv64F);
        var rodrigues = CvInvoke.cvCreateMat(3, 1, DepthType.Cv64F);
        var rotationMat = CvInvoke.cvCreateMat(3, 3, DepthType.Cv64F);
        var intrinsic = CvInvoke.cvCreateMat(3, 3, DepthType.Cv64F);
        var distortion = CvInvoke.cvCreateMat(1, 4, DepthType.Cv64F);
        var x = default(double);
        var y = default(double);

        for (int r = 0; r < 3; r++)
        {
            for (int k = 0; k < 4; k++)
            {
                CvInvoke.cvSetReal2D(worldPoints, r, k, this.PointMap2[k].ECEF[r]);
            }
        }

        for (int k = 0; k < 4; k++)
        {
            x = (this.PointMap2[k].Point[0] - 0.5) * this.Width;
            y = (this.PointMap2[k].Point[1] - 0.5) * this.Height;

            CvInvoke.cvSetReal2D(imagePoints, 0, k, x);
            CvInvoke.cvSetReal2D(imagePoints, 1, k, y);
        }

        for (int r = 0; r < 3; r++)
        {
            for (int c = 0; c < 3; c++)
            {
                CvInvoke.cvSetReal2D(intrinsic, r, c, this.Coeffs[r, c]);
            }
        }

       CvInvoke.cvZero(rodrigues);
       CvInvoke.cvZero(translation);
       CvInvoke.cvZero(distortion);

       CvInvoke.cvFindExtrinsicCameraParams2(worldPoints, imagePoints, intrinsic, 
       distortion, rodrigues, translation);
       CvInvoke.cvRodrigues2(rodrigues, rotationMat);`

**Comment by emgucv** [comment]
Please post this ticket on Emgu CV instead of Emgu TF.

Closing ticket now.
