### ISSUE TITLE
tfextern.dll missing

### ISSUE THREAD

**Issue by faycalkadri** [emgucv/emgutf#16]
When building Multiboxdetection project (windows Desktop), I got this error:
'This package do not contain necessary binary for WindowsForms. X64 is targeted, but file C:\emgutf-master\emgutf-master\Emgu.TF\..\lib\x64\tfextern.dll is missing.'	MultiboxPeopleDetection	C:\emgutf-master\emgutf-master\Emgu.TF\Emgu.TF.projitems	217

**Comment by emgucv** [comment]
The native binary is not checked into the Git repo. You will need to build it using the script at "platforms\windows\build_tf_x86_64.bat". You will need to have CMake and Visual Studio installed on a workstation with at least 16 GB of memory.

**Comment by superdan0812** [comment]
I am seeing this same issue. Has anyone found a solution?

**Comment by emgucv** [comment]
Closing ticket now.
