### ISSUE TITLE
GetAllocator() is not implemented

### ISSUE THREAD

**Issue by LizaBlignaut** [emgucv/emgutf#19]
I am using EmguTF 1.7.0.174 for a neural network trained with Python with Tensorflow 1.7. I froze the neural network and then load that with Emgu. The implementation worked on my PC, but my application gives this error on another PC where I installed it:
C:\bb\tf_x64\build\tensorflow\tensorflow/core/framework/device_base.h:168] GetAllocator() is not implemented.
The second PC does not have Tensorflow installed and also does not have a GPU. But since I use the free license, which doesn't have GPU support, I don't think that will be the problem.
It also only does it after the application has been running for a while. So it is able to load the neural network and apply it successfully a few times and then it crashes with that error.
What can be the cause of this?

**Comment by emgucv** [comment]
Tensorflow installation is not required when using Emgu TF. The library contains all the binary needed to execute tensorflow graph. 

We have not seem this problem happens on our workstations. Have you try the latest 1.13.1 release and see if that works?

**Comment by LizaBlignaut** [comment]
I tried 1.12 and now I get this error:
F tensorflow/core/framework/device_base.cc:33] Device does not implement name()
And
panic: attempt to nsync_mu_unlock() an nsync_mu held in read mode

**Comment by LizaBlignaut** [comment]
I realized I never disposed the Session when I am done. Now that I dispose it before I create a new Session with the same graph, I no longer get the error.

**Comment by emgucv** [comment]
Thanks for the update. Closing ticket for now.
