### ISSUE TITLE
System Exception: 'No OpKernel was registered to support Op 'QuantizeV2' with these attrs.  

### ISSUE THREAD

**Issue by fastlater** [emgucv/emgutf#2]
Dear developers and community,

I know that the tutorial section for emgutf is under construction but I have been testing by myself your example codes. The inception and multibox models are working fine and the examples are easy to follow. However, when I tried the Stylize model, an error is displayed:
System.Exception: 'No OpKernel was registered to support Op 'QuantizeV2' with these attrs.  
My demo code is as below:
          StylizeGraph graph = new StylizeGraph();
            Tensor imageTensor = ImageIO.ReadTensorFromImageFile(fileName, 224, 224, 128.0f, 1.0f / 128.0f);
            Tensor result = graph.Stylize(imageTensor, 2);
            byte[] imgData = ImageIO.EncodeJpeg(result, 1, 0);
            Bitmap bmp;
            using (var ms = new MemoryStream(imgData))
            {
                bmp = new Bitmap(ms);
                resultPictureBox.Image = bmp;
            }
So my question is:
Does the style variable (value is 2) incorrect? I didnt know what to type there so I tested any random number.
Does the input tensor "imageTensor" incorrectly defined?
EmguTF stylize model is not working yet?

I am newbie on tensorFlow and this is my first time posting in github so sorry in advance if the Issue section is not a forum to ask for problems related to codes. Also, I would like to know if we already can retrain the inception final layers (transfer learning) using emguTF.

**Comment by emgucv** [comment]
Hi, 

This is a limitation of Tensorflow.

The Windows release of Tensorflow can only be built with CMake, but the CMake build currently do not support compilation for the "QuantizeV2" function. See the README.md file here:
https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/cmake
Browse down and you will see this:

> Current Status
> 
> CMake can be used to build TensorFlow on Windows. See the getting started documentation for instructions on how to install a pre-built TensorFlow package on Windows.
> 
> Current known limitations
> 
> It is not possible to load a custom Op library.
> GCS file system is not supported.
> The following Ops are not currently implemented:
> Dequantize
> QuantizeAndDequantize
> QuantizedAvgPool
> QuantizedBatchNomWithGlobalNormalization
> QuantizedBiasAdd
> QuantizedConcat
> QuantizedConv2D
> QuantizedMatmul
> QuantizedMaxPoo
> QuantizeDownAndShrinkRange
> QuantizedRelu
> QuantizedRelu6
> QuantizedReshape
> QuantizeV2
> RequantizationRange
> Requantize 

For this reason, the "StylizeGraph" class can only be used on mobile platform such as Android and iOS at this moment.

It needed to be fixed from the Tensorflow cmake build script.

**Comment by fastlater** [comment]
Thank you for your reply.
