### ISSUE TITLE
Build the binary in CentOS Error

### ISSUE THREAD

**Issue by wesson2016** [emgucv/emgutf#24]
when i build Emgu CV by calling make command in CentOS 7,  the compile was failed, there is an error like this:
`[ 95%] Building CXX object Emgu.CV.Extern/CMakeFiles/cvextern.dir/vector_ERStat.cpp.o
In file included from /usr/local/src/emgucv/opencv/modules/core/include/opencv2/core.hpp:56:0,
                 from /usr/local/src/emgucv/opencv/modules/core/include/opencv2/core/types_c.h:124,
                 from /usr/local/src/emgucv/opencv/modules/core/include/opencv2/core/core_c.h:48,
                 from /usr/local/src/emgucv/Emgu.CV.Extern/vectors_c.h:12,
                 from /usr/local/src/emgucv/Emgu.CV.Extern/vector_ERStat.h:15,
                 from /usr/local/src/emgucv/Emgu.CV.Extern/vector_ERStat.cpp:10:
/usr/local/src/emgucv/opencv/modules/core/include/opencv2/core/traits.hpp: In instantiation of ‘struct cv::traits::Type<cv::text::ERStat>’:
/usr/local/src/emgucv/opencv/modules/core/include/opencv2/core/mat.inl.hpp:95:32:   required from ‘cv::_InputArray::_InputArray(const std::vector<_RealType>&) [with _Tp = cv::text::ERStat]’
/usr/local/src/emgucv/Emgu.CV.Extern/vector_ERStat.cpp:77:35:   required from here
/usr/local/src/emgucv/opencv/modules/core/include/opencv2/core/traits.hpp:386:8: 错误：‘type’不是‘cv::DataType<cv::text::ERStat>’的成员
 { enum { value = DataType<T>::type }; };
        ^
make[2]: *** [Emgu.CV.Extern/CMakeFiles/cvextern.dir/vector_ERStat.cpp.o] 错误 1
make[1]: *** [Emgu.CV.Extern/CMakeFiles/cvextern.dir/all] 错误 2
make: *** [all] 错误 2`
I need a help or guide!!

**Comment by emgucv** [comment]
This is the bug tracker for Emgu TF. Please open a bug here for Emgu CV issues:
https://github.com/emgucv/emgucv/issues
