### ISSUE TITLE
Sample Screen for COCO SSD Mobilenet Not provided

### ISSUE THREAD

**Issue by ShubhamSureWash** [emgucv/emgutf#27]
On using COCO TFLIte model, I am getting weird results, model working fine in python but not in unity.

**Comment by emgucv** [comment]
Hi, can you share the model, a sample image and the python code to test the model? Please also shared the Unity code to load the model so we can reproduce the issue on our side. You can also email them to support@emgu.com if you do not want to share the model here in public.
