### ISSUE TITLE
Emgu TF Lite behavior changes for different devices

### ISSUE THREAD

**Issue by ShubhamSureWash** [emgucv/emgutf#29]
Hello, We are developing a Computer Vision-based cross-platform application in Unity. We are using Emgu TF Lite v14.unitypackage to Integrate integrate our TFLite model to Unity. We have noticed that the same model takes different time to process each frame when tested using Emgu(Unity) in the android and sample Android Studio project provided with Tensorflow. The application developed using Android Studio takes around half the time to process each frame compared to the Emgu TF Lite plugin in Android. The processing time for each frame is around 40-45 millisecond for iOS(tested on 3 devices iPhone XS Max, iPhone 7, and iPad 6th generation ) when using multithreading. Whereas processing time for each frame is around 200+ ms in Pixel 3, 500+ ms in Samsung S7 and on lower devices it's, even more, worst(That too after multi-threading).

1) Can you please look into the performance of the TF-Lite plugin in android. It works well in iOS but not in Android.
2) Can you please provide a multi-thread version for MobileNet and MobileNet COCO SSD example scene?
3) Can you please provide a list of devices that supports your Plugin and how much FPS are you able to achieve in each of these devices when using multi-threading.

**Comment by emgucv** [comment]
On my Galaxy S10, I am able to process the MobileNet Coco SSD example scene on ~140 ms.

I noticed that on Android devices, it default to have NNAPI  ( Android Neural Networks API ) enabled. On my Galaxy S10 device that seem to slowed down the computation. Calling Interpreter.UseNNAPI(false) force it to not use NNAPI and use the CPU instead. Which actually give me faster process time. 

With NNAPI disabled, I am able to processed a frame at ~80 ms compares with 140 ms. 

There is an open ticket on tflite that describing this issues:
https://github.com/tensorflow/tensorflow/issues/28283

**Comment by ShubhamSureWash** [comment]
Thanks a lot for your help. It worked.
