### ISSUE TITLE
Not working for IL2CPP for Android build

### ISSUE THREAD

**Issue by ruttlej** [emgucv/emgutf#32]
Unity version: 2019.1.12 or 2019.2.2 or 2019.3.0
Emgu.TF.Lite plugin version: 1.15

When I use the Unity Emgu TF Lite plugin and try to build for Android using the IL2CPP scripting backend and try to create the FlatBufferModel you get an exception:
Unsupported internal call for IL2CPP:Assembly::GetManifestModuleInternal - "This icall is not supported by il2cpp"

I need to build using IL2CPP because the play store only accepts 64 bit builds, and you can only build arm64 if you run IL2CPP scripting backing. 

The problem can be recreated by starting a new project, importing the Emgu.TF.Lite 1.15 plugin from the asset store, switch the build to android and selecting the scripting backend to IL2CPP and running the demo project CocoSsdMobilenet from the plugin on an android device. (I used a Google Pixel 3). The project works perfectly with the "Mono" scripting backend. but then I can't build to arm64. 

Any help would be greatly appreciated

**Comment by emgucv** [comment]
Just tested with Emgu TF Lite 1.15 release, using IL2CPP backend and .Netstandard 2.0 API level. C++ compiler configuration is set to "Release". Both Armv7 and Arm64 enabled. Unity 2019.3.0f6 on Windows. Compiled to APK and deployed to Galaxy S10 running Android 10. Using demo project CocoSsdMobilenet. Works without issues.

The specific bug you mention is associated to the use of System.Reflection.Assembly.GetManifestModule function:
https://docs.microsoft.com/en-us/dotnet/api/system.reflection.assembly.manifestmodule?view=netstandard-2.0
It is not used in any of the Emgu TF Lite source code.

**Comment by emgucv** [comment]
Closing ticket now
