### ISSUE TITLE
Loading x86/x64 native DLLs briefly change Environment.CurrentDirectory which leads to RANDOM CRASHES

### ISSUE THREAD

**Issue by vpenades** [emgucv/emgutf#44]
I am using Emgu.TF in a complex project, where Emgu components are initialized and used in their own thread. Meanwhile, the main thread runs its own logic, which includes loading lots of files.

When Emgu loads its native DLLs, it briefly sets `Environment.CurrentDirectory` to point to the x86 or x64 path where the native DLLs are located.

When that happens, and at the same time another thread is also loading files, the CurrentDirectory change will mess the paths for all threads and will cause `FileNotFound` exceptions.

Furthermore, if another thread that is loading files, happens to change CurrentDirectory, it will break the process of loading TF native DLLs with a similar crash.

The offending methods are:

- [TF LoadUnmanagedModules](https://github.com/emgucv/emgutf/blob/4c8f65ddf0379e90a5c66bf4abd60d5e9be6174a/Emgu.TF/TFInvoke.cs#L56)
  - [CurrentDirectory assignment](https://github.com/emgucv/emgutf/blob/4c8f65ddf0379e90a5c66bf4abd60d5e9be6174a/Emgu.TF/TFInvoke.cs#L134)
- [TFLite LoadUnmanagedModules](https://github.com/emgucv/emgutf/blob/4c8f65ddf0379e90a5c66bf4abd60d5e9be6174a/Emgu.TF.Lite/TFLiteInvoke.cs#L85)
  - [CurrentDirectory assignment](https://github.com/emgucv/emgutf/blob/4c8f65ddf0379e90a5c66bf4abd60d5e9be6174a/Emgu.TF.Lite/TFLiteInvoke.cs#L174)

I haven't checked Emgu.CV, but maybe it's also affected.

This is IMHO a very bad design, because it changes a process wide property in a non blocking way... essentially making the use of multithreading _dangerous and crash prone_.

### Alternatives:

Refrain from using `System.Environment.CurrentDirectory` and instead, use these APIs:

- [AddDllDirectory](https://docs.microsoft.com/en-us/windows/win32/api/libloaderapi/nf-libloaderapi-adddlldirectory)
- [RemoveDllDirectory](https://docs.microsoft.com/en-us/windows/win32/api/libloaderapi/nf-libloaderapi-removedlldirectory)

These methods can be P/Invoked from c# to set additional Native LoadLibrary paths, so before loading the native libraries, you call AddDllDirectory, and when finished, you can call RemoveDllDirectory, or just leave it that way to ensure further LoadLibrary calls will also search in that directory.

This has the advantage that it doesn't change the application's current directory.

Btw, I've used these APIs in the past, they're the real deal for loading natives from multiple paths, because they don't affect in any way the loading paths of managed libraries.

**Comment by emgucv** [comment]
Fixed in this commit:
https://github.com/emgucv/emgutf/commit/3f293b9cb436f95632edfc233c3831331c7200b6 
Use AddDllDirectory instead of setting System.Environment.CurrentDirectory for Windows.
