### ISSUE TITLE
No Interpreter.Run(input, output) ? And how can i make a prediction with my tflite model

### ISSUE THREAD

**Issue by minhduc66532** [emgucv/emgutf#47]
No Run method can be found in Interpreter class. How can i make a prediction with my tflite model ? I did all kinds of research and found can't found a SINGLE tutorial on how to make a prediction with tflite. Any ideas ?

**Comment by emgucv** [comment]
Tensorflow Lite use the Invoke function to run the graph, see the C API here:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/c/c_api.h#L208
The corresponding TF Lite function in Emgu TF Lite is:
http://www.emgu.com/wiki/files/emgutf/2.4.0/document-lite/html/c64acedf-3a3c-f78b-4aea-d3513ec38bed.htm

Our release package contains demo projects to show to to make prediction with tflite. Please download the release package and open the Visual Studio solution under the "Solution" folder to give it a try.

You can also find some source code here:
https://github.com/emgucv/emgutf/tree/master/Emgu.TF.Lite.Models
that demonstrate how to use CocoSSDMobileNet, Inception or MobileNet tflite models with Emgu TF Lite.

**Comment by minhduc66532** [comment]
Thank you for the answer. But i'm still have some more question

1. How to read a tensor from a mat ? There is no NativeImageIO.ReadTensorFromMat() method only ReadMatFromFile
2. How to convert back from output tensor to mat ?
3. How to make tflite to run on GPU ?

**Comment by minhduc66532** [comment]
@emgucv May i suggest that the problem isn's solved yet ? It has been 3 days and i'm running out of ideas how to solve this myself. Thank you
