### ISSUE TITLE
Is there any difference between Emgu.TF.Tensor and  Emgu.TF.Lite.Tensor

### ISSUE THREAD

**Issue by minhduc66532** [emgucv/emgutf#48]
The title say it all. Thank you for all of your answer

**Comment by emgucv** [comment]
Emgu TF is the .Net wrapper for Tensorflow. Emgu.TF.Tensor is a Tensorflow Tensor.

Emgu TF Lite is the .Net wrapper for Tensorflow Lite. Emgu.TF.Lite.Tensor is a Tensorflow Lite Tensor.

If you wonder what is the different between Tensorflow and Tensorflow lite, here are some references:
https://en.wikipedia.org/wiki/TensorFlow#TensorFlow_Lite
https://www.quora.com/What-is-the-difference-between-TensorFlow-and-TensorFlow-lite

**Comment by minhduc66532** [comment]
Ahh ok, thanks
