### ISSUE TITLE
Can provide c# load tf2 save model and Recognize Example, thanks

### ISSUE THREAD

**Issue by jackswei** [emgucv/emgutf#52]

**Comment by jackswei** [comment]
i use UnitTest1.cs ex, but  resnet is null


string[] modelFile = new string[2];
                      modelFile[0] = System.IO.Path.Combine(System.Environment.CurrentDirectory, "tf\\resnet_50_classification_1.zip");
                    modelFile[1] = catalogPath;     

    using (Tensor imageTensor = ImageIO.ReadTensorFromImageFile<float>("Bird2.png",224, 224, 0, 1.0f/255.0f))
                    using (Resnet resnet = new Resnet())
                    {
                         resnet.Init(modelFile);                        
                        MetaGraphDef metaGraphDef = MetaGraphDef.Parser.ParseFrom(resnet.MetaGraphDefBuffer.Data);
                        var signatureDef = metaGraphDef.SignatureDef["serving_default"];
                        var inputNode = signatureDef.Inputs;
                        var outputNode = signatureDef.Outputs;

                        HashSet<string> opNames = new HashSet<string>();
                        HashSet<string> couldBeInputs = new HashSet<string>();
                        HashSet<string> couldBeOutputs = new HashSet<string>();
                        foreach (Operation op in resnet.Graph)
                        {

                            String name = op.Name;
                            opNames.Add(name);

                            if (op.NumInputs == 0 && op.OpType.Equals("Placeholder"))
                            {
                                couldBeInputs.Add(op.Name);
                                AttrMetadata dtypeMeta = op.GetAttrMetadata("dtype");
                                AttrMetadata shapeMeta = op.GetAttrMetadata("shape");
                                Emgu.TF.DataType type = op.GetAttrType("dtype");
                                Int64[] shape = op.GetAttrShape("shape");
                                Emgu.TF.Buffer valueBuffer = op.GetAttrValueProto("shape");
                                 Emgu.TF.Buffer shapeBuffer = op.GetAttrTensorShapeProto("shape");
                                Tensorflow.TensorShapeProto shapeProto =
                                    Tensorflow.TensorShapeProto.Parser.ParseFrom(shapeBuffer.Data);
                            }

                            if (op.OpType.Equals("Const"))
                            {
                                AttrMetadata dtypeMeta = op.GetAttrMetadata("dtype");
                                AttrMetadata valueMeta = op.GetAttrMetadata("value");
                                using (Tensor valueTensor = op.GetAttrTensor("value"))
                                {
                                    var dim = valueTensor.Dim;
                                }
                            }

                            if (op.OpType.Equals("Conv2D"))
                            {
                                AttrMetadata stridesMeta = op.GetAttrMetadata("strides");
                                AttrMetadata paddingMeta = op.GetAttrMetadata("padding");
                                AttrMetadata boolMeta = op.GetAttrMetadata("use_cudnn_on_gpu");
                                Int64[] strides = op.GetAttrIntList("strides");
                                bool useCudnn = op.GetAttrBool("use_cudnn_on_gpu");
                                String padding = op.GetAttrString("padding");
                            }

                            foreach (Output output in op.Outputs)
                            {
                                int[] shape = resnet.Graph.GetTensorShape(output);
                                if (output.NumConsumers == 0)
                                {
                                    couldBeOutputs.Add(name);
                                }
                            }

                             Emgu.TF.Buffer buffer = resnet.Graph.GetOpDef(op.OpType);
                            Tensorflow.OpDef opDef = Tensorflow.OpDef.Parser.ParseFrom(buffer.Data);
                        }

                        using ( Emgu.TF.Buffer versionDef = resnet.Graph.Versions())
                        {
                            int l = versionDef.Length;
                        }

                        Resnet.RecognitionResult[] results = resnet.Recognize(imageTensor);

                    }

**Comment by emgucv** [comment]
FYI, the Emgu TF release package's Xamarin Forms demo also contains a sample Resnet implementation that load saved model:
https://github.com/emgucv/emgutf/blob/master/Emgu.TF.Models/Resnet.cs
https://github.com/emgucv/emgutf/blob/master/Emgu.TF.Example/XamarinForms/XamarinForms/ResnetPage.cs
