### ISSUE TITLE
ARM64 for Emgu.TF.Lite.Runtime.Ubuntu

### ISSUE THREAD

**Issue by keesschollaart81** [emgucv/emgutf#56]
Thanks for the awesome work. 

Am I correct in that the Emgu.TF.Lite does not run OOB on Ubuntu ARM64? If so, what would be the best approach to get this to work? 

My intent is to flash a RPi 4 with Ubuntu 20.04 (I'm fine with both 32 and 64 bits). 

I'm willing to spend time on a PR to make this happen but wanted to consult you about the approach first!

**Comment by emgucv** [comment]
You will need to build the binary from source code.

I have updated the instructions here:
http://www.emgu.com/wiki/index.php/Emgu_TF_Download_And_Installation#Ubuntu_20.04

The instructions are for ubuntu x64 but should also work for Ubuntu 20.04 (ARM64 / ARM)  for raspberry.

**Comment by keesschollaart81** [comment]
Clear! Thanks.
