### ISSUE TITLE
Emgu.runtime.windows.msvc.rt.x64 version conflict between Emgu.CV and Emgu.TF

### ISSUE THREAD

**Issue by vpenades** [emgucv/emgutf#62]
I have a project that uses both Emgu.CV and Emgu.TF.

Two day ago you updated Emgu.TF, which now uses the shared native libraries packages, to prevent binary overwriting as described in issues #61 https://github.com/emgucv/emgucv/issues/371

|Package|Version| msvc.rt.x64 version|
|-|-|-|
|Emgu.CV.runtime.windows|4.5.1.4349|19.28.29336|
|Emgu.TF.runtime.windows|2.4.1.1202|19.28.29337|

As you can see, the two libraries use different version of the underlaying shared dependencies, __which causes the compilation to fail due to version mismatch.__

### Temporary solution

There's a hack to solve the issue, which is to reference `Emgu.runtime.windows.msvc.rt.x64` explicitly;

```xml
    <PackageReference Include="Emgu.CV.runtime.windows" Version="4.5.1.4349" />
    <PackageReference Include="Emgu.TF.runtime.windows" Version="2.4.1.1202" />
    <PackageReference Include="Emgu.runtime.windows.msvc.rt.x64" Version="19.28.29337" />
```

Things are made more complicated because since `Emgu.runtime.windows.msvc.rt.x64` is hidden from indexing, the reference needs to be added manually by editing the csproj file.

After this fix, it works, but Visual Studio is not dumb and reminds me in the solution explorer like this:

![imagen](https://user-images.githubusercontent.com/5433822/112478622-7bf04a00-8d74-11eb-9ed2-fcace448b63f.png)

### Expected solution

Ideally, Both Emgu.CV and Emgu.TF  (and eventually, Emgu.TF.Lite) should use the same shared package versions, so they can play together nicely.

**Comment by emgucv** [comment]
Thanks for pointing that out.

It has been fixed on Emgu CV side: https://github.com/emgucv/emgucv/commit/0fce4449f52ea825416d7578c11856e887fa32bd

Instead of using a fixed version of MSVCRT (e.g. =19.28.29336) , the dependency on Emgu.CV.runtime.windows nuget package will now allow using more recent version of MSVCRT (e.g. >= 19.28.29336).

**Comment by vpenades** [comment]
Thanks!

It could be nice if you could update the nuget packages more often, even with a prerelease postfix.... that would allow us to catch these changes sooner.
