### ISSUE TITLE
NuGet Package not up to date

### ISSUE THREAD

**Issue by sebastianhaeni** [emgucv/emgutf#8]
The latest NuGet package of Emgu.TF has version 1.2.0.26. 
The latest release available on SourceForge is 1.4.0. 

Also the namespaces available in the NuGet package are Emgu.TF, Emgu.Util and Emgu.TF.Util.TypeEnum. Everything else is missing.

Can you please sync the two release flows and update the NuGet package to the same thing as I can download on SourceForge?

**Comment by emgucv** [comment]
Done, the 1.4 release has been updated in nuget.

**Comment by emgucv** [comment]
Closing issue now, thanks for reporting
