### ISSUE TITLE
DllNotFoundException: tfliteextern in unity on MacOS 

### ISSUE THREAD

**Issue by mmf007** [emgucv/emgutf#88]
Hello!
When installing Emgu CV and Emgu TF Lite packages together in unity 2020.3.23 on MacOS. When running your example from Emgu.TF.Lite\Demo\MobilenetScene.unity an error occurs.

DllNotFoundException: tfliteextern assembly:<unknown assembly> type:<unknown type> member:(null)
Emgu.TF.Lite.TfLiteInvoke..cctor () (at Assets/Emgu.TF.Lite/Assets/Scripts/Emgu.TF.Lite/TFLiteInvoke.cs:494)
Rethrow as DllNotFoundException: Unable to load native binary. Please make sure a proper Emgu.TF.Lite.runtime.{platform} nuget package is added, or make sure the native binary can be found in the folder of the executable.
Emgu.TF.Lite.TfLiteInvoke..cctor () (at Assets/Emgu.TF.Lite/Assets/Scripts/Emgu.TF.Lite/TFLiteInvoke.cs:502)
Rethrow as TypeInitializationException: The type initializer for 'Emgu.TF.Lite.TfLiteInvoke' threw an exception.
MobilenetBehavior+<Start>d__6.MoveNext () (at Assets/Emgu.TF.Lite/Demo/MobilenetBehavior.cs:34)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at /Users/bokken/build/output/unity/unity/Runtime/Export/Scripting/Coroutines.cs:17) 

Tried to put everything in a new project. Same error.

Help me please.

**Comment by emgucv** [comment]
Are you using unity 2020.3.23 with MacOS on apple silicon (arm64) or intel (x64)?

**Comment by mmf007** [comment]
One Emgu TF Lite without Emgu CV works well.

**Comment by emgucv** [comment]
Just created a new Unity 3D project using Unity 2020.3.31f1. Imported Emgu CV 4.6.0.5131 & Emgu TF Lite 2.10.1.1493 from Unity Asset Store. Opened the demo scene under "Emgu.TF.Lite\Demo\MobileNetScene", run the scene and it is working as expected. Mac OS Ventura 13.4 on Intel x64 cpu:
![image](https://github.com/emgucv/emgutf/assets/2035816/24851088-3744-4cc6-8bb1-39f709491622)

**Comment by emgucv** [comment]
Closing ticket now.
